"""optimization_indexes

Revision ID: 24133a74a737
Revises: 719b8866c096
Create Date: 2026-01-27 09:07:42.991366

"""

from alembic import op
import sqlalchemy as sa

revision = '24133a74a737'
down_revision = '719b8866c096'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_outbox_next_attempt_at_utc'), 'event_outbox', ['next_attempt_at_utc'], unique=False)
    op.create_index(op.f('ix_event_outbox_sent_at_utc'), 'event_outbox', ['sent_at_utc'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_dept'), 'tickets', ['assigned_dept'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_to_user_id'), 'tickets', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_sla_breach_sent'), 'tickets', ['sla_breach_sent'], unique=False)
    op.create_index(op.f('ix_tickets_sla_warning_sent'), 'tickets', ['sla_warning_sent'], unique=False)
    op.create_index(op.f('ix_tickets_source'), 'tickets', ['source'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_source'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_warning_sent'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_breach_sent'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_dept'), table_name='tickets')
    op.drop_index(op.f('ix_event_outbox_sent_at_utc'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_next_attempt_at_utc'), table_name='event_outbox')
    # ### end Alembic commands ###
