"""add_full_name_column_to_users

Revision ID: 30074ed22c57
Revises: 0009_add_ticket_dept
Create Date: 2026-01-19 04:21:47.770990

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "30074ed22c57"
down_revision = "0009_add_ticket_dept"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Fixed: Removed auto-generated DROP hq_users statement
    # hq_users is an HQ table that should not be dropped when running Plant migrations
    op.create_index(op.f("ix_assets_name"), "assets", ["name"], unique=False)
    op.create_index(
        op.f("ix_audit_log_created_at_utc"), "audit_log", ["created_at_utc"], unique=False
    )
    op.alter_column(
        "tickets",
        "source",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("'MANUAL'::character varying"),
    )
    op.create_index(op.f("ix_tickets_created_at_utc"), "tickets", ["created_at_utc"], unique=False)
    op.create_index(op.f("ix_tickets_sla_due_at_utc"), "tickets", ["sla_due_at_utc"], unique=False)
    op.add_column("users", sa.Column("full_name", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    op.drop_index(op.f("ix_tickets_sla_due_at_utc"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_at_utc"), table_name="tickets")
    op.alter_column(
        "tickets",
        "source",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
        existing_server_default=sa.text("'MANUAL'::character varying"),
    )
    op.drop_index(op.f("ix_audit_log_created_at_utc"), table_name="audit_log")
    op.drop_index(op.f("ix_assets_name"), table_name="assets")
    op.create_table(
        "hq_users",
        sa.Column("username", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("pin_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "roles",
            sa.VARCHAR(length=256),
            server_default=sa.text("'admin'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("username", name=op.f("hq_users_pkey")),
    )
    # ### end Alembic commands ###
