"""integrate_batch_23_schema

Revision ID: 6d85ac6521e8
Revises: f435f62edfb2
Create Date: 2026-01-14 12:04:26.517980

"""

from alembic import op
import sqlalchemy as sa

revision = '6d85ac6521e8'
down_revision = 'f435f62edfb2'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Assets
    op.create_table('assets',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('site_code', sa.String(length=16), nullable=False),
        sa.Column('asset_code', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('category', sa.String(length=128), nullable=False),
        sa.Column('parent_id', sa.String(length=64), nullable=True),
        sa.Column('criticality', sa.String(length=32), nullable=False, server_default='medium'),
        sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('location_area', sa.String(length=128), nullable=True),
        sa.Column('location_line', sa.String(length=128), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='active'),
        sa.Column('created_at_utc', sa.DateTime(), nullable=False),
        sa.Column('updated_at_utc', sa.DateTime(), nullable=True),
        sa.Column('created_by_user_id', sa.String(length=64), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=False)
    op.create_index(op.f('ix_assets_parent_id'), 'assets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_assets_site_code'), 'assets', ['site_code'], unique=False)

    # 2. Master Types
    op.create_table('master_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('site_code', sa.String(length=16), nullable=False),
        sa.Column('type_code', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at_utc', sa.DateTime(), nullable=False),
        sa.Column('updated_at_utc', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('site_code', 'type_code', name='uq_master_types_site_type')
    )
    op.create_index(op.f('ix_master_types_site_code'), 'master_types', ['site_code'], unique=False)

    # 3. Master Items
    op.create_table('master_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('site_code', sa.String(length=16), nullable=False),
        sa.Column('master_type_code', sa.String(length=64), nullable=False),
        sa.Column('item_code', sa.String(length=64), nullable=False),
        sa.Column('item_name', sa.String(length=160), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('meta_json', sa.JSON(), nullable=False, server_default='{}'),
        sa.Column('created_at_utc', sa.DateTime(), nullable=False),
        sa.Column('updated_at_utc', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('site_code', 'master_type_code', 'item_code', name='uq_master_items_site_type_code')
    )
    op.create_index(op.f('ix_master_items_master_type_code'), 'master_items', ['master_type_code'], unique=False)
    op.create_index(op.f('ix_master_items_site_code'), 'master_items', ['site_code'], unique=False)

    # 4. Reason Suggestions
    op.create_table('reason_suggestions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('site_code', sa.String(length=16), nullable=False),
        sa.Column('master_type_code', sa.String(length=64), nullable=False, server_default='STOP_REASON'),
        sa.Column('suggested_name', sa.String(length=256), nullable=False),
        sa.Column('normalized_key', sa.String(length=256), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('status', sa.String(length=24), nullable=False, server_default='pending'),
        sa.Column('threshold', sa.Integer(), nullable=False, server_default='5'),
        sa.Column('last_examples_json', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('approved_master_item_id', sa.Integer(), nullable=True),
        sa.Column('merged_into_master_item_id', sa.Integer(), nullable=True),
        sa.Column('created_by_user_id', sa.String(length=64), nullable=True),
        sa.Column('reviewed_by_user_id', sa.String(length=64), nullable=True),
        sa.Column('reviewed_at_utc', sa.DateTime(), nullable=True),
        sa.Column('created_at_utc', sa.DateTime(), nullable=False),
        sa.Column('updated_at_utc', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reason_suggestions_master_type_code'), 'reason_suggestions', ['master_type_code'], unique=False)
    op.create_index(op.f('ix_reason_suggestions_normalized_key'), 'reason_suggestions', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_reason_suggestions_site_code'), 'reason_suggestions', ['site_code'], unique=False)

    # 5. Report Requests
    op.create_table('report_requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('site_code', sa.String(length=16), nullable=False),
        sa.Column('report_type', sa.String(length=64), nullable=False),
        sa.Column('date_from', sa.DateTime(), nullable=False),
        sa.Column('date_to', sa.DateTime(), nullable=False),
        sa.Column('filters_json', sa.Text(), nullable=False, server_default='{}'),
        sa.Column('requested_by_user_id', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('generated_file_path', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at_utc', sa.DateTime(), nullable=False),
        sa.Column('updated_at_utc', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_requests_report_type'), 'report_requests', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_requests_site_code'), 'report_requests', ['site_code'], unique=False)
    op.create_index(op.f('ix_report_requests_status'), 'report_requests', ['status'], unique=False)

    op.alter_column('tickets', 'source',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'source',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    # ### end Alembic commands ###
