"""rename_location_line_to_sub_location_area

Revision ID: ae0e6507cf84
Revises: 24133a74a737
Create Date: 2026-02-19 05:39:20.417114

"""

from alembic import op

revision = "ae0e6507cf84"
down_revision = "24133a74a737"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "location_line", new_column_name="sub_location_area")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "sub_location_area", new_column_name="location_line")
    # ### end Alembic commands ###
