"""add_station_model

Revision ID: f435f62edfb2
Revises: 0006_assets
Create Date: 2026-01-13 09:58:13.929876

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "f435f62edfb2"
down_revision = "0006_assets"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Fixed: Removed auto-generated DROP statements for HQ tables
    # This migration should only create the stations table for Plant DB
    op.create_table(
        "stations",
        sa.Column("station_code", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("secret_hash", sa.String(length=128), nullable=False),
        sa.Column("token_salt", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("station_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_source_event"),
        "ingest_dedup",
        ["source_id", "event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_event_outbox_next_attempt_at_utc"),
        "event_outbox",
        ["next_attempt_at_utc"],
        unique=False,
    )
    op.create_table(
        "hq_plants",
        sa.Column("site_code", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=128),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("last_seen_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("site_code", name=op.f("hq_plants_pkey")),
    )
    op.create_table(
        "applied_correlation",
        sa.Column("correlation_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("created_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("correlation_id", name=op.f("applied_correlation_pkey")),
    )
    op.create_table(
        "ticket_snapshot",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_code", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("ticket_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("asset_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "title",
            sa.VARCHAR(length=256),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'OPEN'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.VARCHAR(length=32),
            server_default=sa.text("'MEDIUM'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("sla_due_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "acknowledged_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("resolved_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("ticket_snapshot_pkey")),
        sa.UniqueConstraint(
            "site_code",
            "ticket_id",
            name=op.f("uq_ticket_site_ticket"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_ticket_snapshot_ticket_id"), "ticket_snapshot", ["ticket_id"], unique=False
    )
    op.create_index(op.f("ix_ticket_snapshot_status"), "ticket_snapshot", ["status"], unique=False)
    op.create_index(
        op.f("ix_ticket_snapshot_site_code"), "ticket_snapshot", ["site_code"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_snapshot_asset_id"), "ticket_snapshot", ["asset_id"], unique=False
    )
    op.create_table(
        "hq_timeline_event",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_code", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("occurred_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("asset_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("reason_code", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "duration_seconds",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "payload_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("hq_timeline_event_pkey")),
        sa.UniqueConstraint(
            "site_code",
            "event_id",
            name=op.f("uq_hq_event_site_event"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_hq_timeline_event_site_code"), "hq_timeline_event", ["site_code"], unique=False
    )
    op.create_index(
        op.f("ix_hq_timeline_event_reason_code"), "hq_timeline_event", ["reason_code"], unique=False
    )
    op.create_index(
        op.f("ix_hq_timeline_event_occurred_at_utc"),
        "hq_timeline_event",
        ["occurred_at_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hq_timeline_event_event_type"), "hq_timeline_event", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_hq_timeline_event_event_id"), "hq_timeline_event", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_hq_timeline_event_asset_id"), "hq_timeline_event", ["asset_id"], unique=False
    )
    op.create_table(
        "rollup_daily",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_code", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("day_utc", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column(
            "stops", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "faults", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "tickets_open",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sla_breaches",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "downtime_minutes",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("updated_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("rollup_daily_pkey")),
        sa.UniqueConstraint(
            "site_code",
            "day_utc",
            name=op.f("uq_rollup_site_day"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_rollup_daily_site_code"), "rollup_daily", ["site_code"], unique=False)
    op.create_index(op.f("ix_rollup_daily_day_utc"), "rollup_daily", ["day_utc"], unique=False)
    op.create_table(
        "stop_reason_daily",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_code", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("day_utc", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("reason_code", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "stops", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "downtime_minutes",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stop_reason_daily_pkey")),
        sa.UniqueConstraint(
            "site_code",
            "day_utc",
            "reason_code",
            name=op.f("uq_reason_site_day_reason"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_stop_reason_daily_site_code"), "stop_reason_daily", ["site_code"], unique=False
    )
    op.create_index(
        op.f("ix_stop_reason_daily_reason_code"), "stop_reason_daily", ["reason_code"], unique=False
    )
    op.create_index(
        op.f("ix_stop_reason_daily_day_utc"), "stop_reason_daily", ["day_utc"], unique=False
    )
    op.create_table(
        "hq_insight_daily",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("day_utc", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("site_code", sa.VARCHAR(length=16), autoincrement=False, nullable=True),
        sa.Column("insight_type", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "severity",
            sa.VARCHAR(length=16),
            server_default=sa.text("'LOW'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "detail_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("hq_insight_daily_pkey")),
        sa.UniqueConstraint(
            "day_utc",
            "site_code",
            "insight_type",
            "title",
            name=op.f("uq_insight_day_site_type_title"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_hq_insight_daily_site_code"), "hq_insight_daily", ["site_code"], unique=False
    )
    op.create_index(
        op.f("ix_hq_insight_daily_insight_type"), "hq_insight_daily", ["insight_type"], unique=False
    )
    op.create_index(
        op.f("ix_hq_insight_daily_day_utc"), "hq_insight_daily", ["day_utc"], unique=False
    )
    op.create_table(
        "report_job",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("report_type", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("period_start_utc", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("period_end_utc", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("file_pdf", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column("file_xlsx", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column("created_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("report_job_pkey")),
        sa.UniqueConstraint(
            "report_type",
            "period_start_utc",
            "period_end_utc",
            name=op.f("uq_report_period"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_report_job_report_type"), "report_job", ["report_type"], unique=False)
    op.drop_table("stations")
    # ### end Alembic commands ###
