from __future__ import annotations

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from common_core.db import Base

# Import models based on MIGRATION_TARGET environment variable
# This prevents table name conflicts when running migrations for a specific target
_migration_target = os.environ.get("MIGRATION_TARGET", "plant").lower()

if _migration_target == "hq":
    from apps.hq_backend import models as hq_models  # noqa: F401
else:
    # Default to plant models
    from apps.plant_backend import models as plant_models  # noqa: F401

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


# -----------------------------------------------------------------------------
# Safety Filters: Prevent accidental drops if Plant/HQ share a DB
# -----------------------------------------------------------------------------
PLANT_TABLES = {
    "users",
    "stop_queue",
    "plc_config",
    "plc_tags",
    "tickets",
    "ticket_activities",
    "event_outbox",
    "email_queue",
    "whatsapp_queue",
    "ingest_dedup",
    "timeline_events",
    "audit_log",
    "dead_letter",
    "assets",
    "master_types",
    "master_items",
    "reason_suggestions",
    "report_requests",
    "stations",
    "system_config",
    "alembic_version",
}

HQ_TABLES = {
    "hq_plants",
    "applied_correlation",
    "dead_letter",
    "rollup_daily",
    "ticket_snapshot",
    "hq_timeline_event",
    "stop_reason_daily",
    "email_queue",
    "report_job",
    "hq_insight_daily",
    "hq_users",
    "alembic_version",
}


def include_object(object, name, type_, reflected, compare_to):
    """
    Determines if an object should be included in the autogenerated migration.
    """
    if type_ == "table":
        # If running for Plant, ignore HQ-only tables
        if _migration_target == "plant":
            return not (name in HQ_TABLES and name not in PLANT_TABLES)

        # If running for HQ, ignore Plant-only tables
        if _migration_target == "hq":
            return not (name in PLANT_TABLES and name not in HQ_TABLES)

    return True


target_metadata = Base.metadata


def get_url() -> str:
    # Prefer explicit SQLALCHEMY_DATABASE_URL, otherwise fall back to env used by services.
    for env in ["SQLALCHEMY_DATABASE_URL", "DATABASE_URL", "HQ_DB_URL", "PLANT_DB_URL"]:
        url = os.environ.get(env)
        if url:
            return url
    return ""


def run_migrations_offline() -> None:
    url = get_url()
    if not url:
        raise RuntimeError(
            "DATABASE_URL / SQLALCHEMY_DATABASE_URL must be set for Alembic migrations"
        )
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    url = get_url()
    if not url:
        raise RuntimeError(
            "DATABASE_URL / SQLALCHEMY_DATABASE_URL must be set for Alembic migrations"
        )

    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = url

    connectable = engine_from_config(configuration, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=include_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
